# Docker Compose for Discord Publish Bot - Local Production Testing
# Use this to test the production Docker image locally before Azure deployment

services:
  discord-publish-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: discord-publish-bot-local
    ports:
      - "8000:8000"
    environment:
      # Application Configuration
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      
      # API Configuration  
      - API_HOST=0.0.0.0
      - API_PORT=8000
      
      # Discord Configuration (loaded from .env.local)
      # - DISCORD_BOT_TOKEN=
      # - DISCORD_APPLICATION_ID=
      # - DISCORD_PUBLIC_KEY=
      # - DISCORD_USER_ID=
      # - DISCORD_GUILD_ID=
      
      # GitHub Configuration (loaded from .env.local)
      # - GITHUB_TOKEN=
      # - GITHUB_REPO=
      # - GITHUB_BRANCH=main
      
      # API Security (loaded from .env.local)
      # - API_KEY=
      # - FASTAPI_ENDPOINT=http://localhost:8000
      
      # Publishing Configuration (loaded from .env.local)
      # - SITE_BASE_URL=
      # - DEFAULT_AUTHOR=
    env_file:
      - path: .env.local  # Create from .env.local.example
        required: false
    volumes:
      # Mount logs for local debugging (remove in production)
      - ./logs:/app/logs
    networks:
      - discord-bot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits for testing Azure Container Apps constraints
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Optional: Local monitoring stack for testing
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-local
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - discord-bot-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-local
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - discord-bot-network
    profiles:
      - monitoring

networks:
  discord-bot-network:
    driver: bridge

volumes:
  grafana-data:

# Usage:
# 1. Copy .env.local.example to .env.local and fill in actual values
# 2. Build and run: docker-compose up --build
# 3. Test health: curl http://localhost:8000/health
# 4. Test API docs: http://localhost:8000/docs
# 5. Test Discord interactions: Use Discord Developer Portal
# 6. With monitoring: docker-compose --profile monitoring up --build
#
# Stop: docker-compose down
# Clean rebuild: docker-compose down && docker-compose up --build --force-recreate
